package disorganizzazione.fency

import java.util.Random;

class TriaNomina{

    private var signum : String = "Titius Caius Sempronius"

    init {
        val prenomen = PRENOMINA[genitor.nextInt(PRENOMINA.size)]
        val nomen = NOMINA[genitor.nextInt(NOMINA.size)]
        val cognomen = COGNOMINA[genitor.nextInt(COGNOMINA.size)]
        signum = "$prenomen $nomen $cognomen"
    }

    override fun toString(): String {
        return signum
    }

    companion object {
        private val PRENOMINA = arrayOf(
                "Amulius",
                "Appius",
                "Aulus",
                "Camillus",
                "Decius",
                "Decimus",
                "Drusus",
                "Faustus",
                "Flavius",
                "Gaius",
                "Gallus",
                "Gnaeus",
                "Herius",
                "Hostus",
                "Lucius",
                "Manius",
                "Marcus",
                "Numerius",
                "Opiter",
                "Octavius",
                "Postumus",
                "Primus",
                "Proculus",
                "Publius",
                "Quintus",
                "Secundus",
                "Servius",
                "Sextus",
                "Spurius",
                "Tertius",
                "Tiberius",
                "Titius",
                "Titus",
                "Vibius"
        )

        private val NOMINA = arrayOf(
                "Aurelius",
                "Appuleius",
                "Aemilius",
                "Claudius",
                "Caius",
                "Cassius",
                "Cosinius",
                "Cornelius",
                "Domitius",
                "Expectius",
                "Fabius",
                "Flavius",
                "Fulvius",
                "Furius",
                "Horatius",
                "Hortensius",
                "Hostilius",
                "Iulius",
                "Licinius",
                "Lupus",
                "Manlius",
                "Marcius",
                "Naevius",
                "Octavius",
                "Papirius",
                "Pompilius",
                "Quinctilius",
                "Sancius",
                "Salvius",
                "Sempronius",
                "Servilius",
                "Sidonius",
                "Sulpicius",
                "Terentius",
                "Tullius",
                "Umbrius",
                "Valerius",
                "Verginius",
                "Volumnius"
        )

        private val COGNOMINA = arrayOf(
                "Acacius",
                "Augustus",
                "Baro",
                "Bellus",
                "Bestia",
                "Bonus",
                "Brutus",
                "Caelestius",
                "Caesar",
                "Calenus",
                "Caligula",
                "Calvinus",
                "Calvus",
                "Candidus",
                "Castorius",
                "Castus",
                "Carus",
                "Cato",
                "Celer",
                "Celsus",
                "Cencius",
                "Corvus",
                "Cornix",
                "Cyprianus",
                "Diocletianus",
                "Dominicus",
                "Domitianus",
                "Didicus",
                "Eburnus",
                "Emeritus",
                "Eustacius",
                "Felix",
                "Fastidius",
                "Faustus",
                "Fabula",
                "Fructosis",
                "Fuscus",
                "Gaius",
                "Gordio",
                "Gracilis",
                "Grumio",
                "Gracchus",
                "Globulus",
                "Hilarius",
                "Horatius",
                "Humilus",
                "Iocundus",
                "Italicus",
                "Iovinus",
                "Iustinianus",
                "Liberalis",
                "Linus",
                "Lupis",
                "Latinius",
                "Laurentius",
                "Lepidus",
                "Lunaris",
                "Macro",
                "Magnus",
                "Maius",
                "Major",
                "Merenda",
                "Martialis",
                "Mercator",
                "Musicus",
                "Naevius",
                "Naso",
                "Nepos",
                "Nero",
                "Niger",
                "Nerva",
                "Octavianus",
                "Olympicus",
                "Ovinus",
                "Otho",
                "Paetus",
                "Pansa",
                "Platipus",
                "Primus",
                "Pastor",
                "Pedo",
                "Petrus",
                "Pius",
                "Piso",
                "Plautus",
                "Porcus",
                "Protus",
                "Planta",
                "Pomponius",
                "Pullus",
                "Pulcher",
                "Publicus",
                "Patronus",
                "Praetextus",
                "Quentin",
                "Quietus",
                "Quintillius",
                "Rectus",
                "Regulus",
                "Remus",
                "Rex",
                "Romanus",
                "Romulus",
                "Rufus",
                "Scaevola",
                "Scapula",
                "Scato",
                "Scipio",
                "Scrofa",
                "Seneca",
                "Senilis",
                "Senna",
                "Sempronius",
                "Severus",
                "Silanus",
                "Simplex",
                "Sosius",
                "Superbus",
                "Silvanus",
                "Tacitus",
                "Tertius",
                "Tubero",
                "Tutor",
                "Tibullus",
                "Trimalchio",
                "Titanus",
                "Ulixes",
                "Valerianus",
                "Venator",
                "Vergilius",
                "Verrucosis",
                "Vespasianus",
                "Virilis",
                "Ventor",
                "Verus",
                "Zeno",
                "Zosimus"
        )

        private val genitor = Random()
    }
}